# Copied from https://github.com/GriMel/Kindleo/blob/master/.travis.yml

language: python

sudo: required

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

before_install:
    - sudo mkdir -p /downloads
    - sudo chmod a+rw /downloads
      # Current sip version on ubuntu 17.04: 4.18.1
    - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.18.1/sip-4.18.1.tar.gz -o /downloads/sip.tar.gz
      # Current PyQT4 version on ubuntu 17.04: 4.11.4
    - curl -L http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt-x11-gpl-4.11.4.tar.gz -o /downloads/pyqt4.tar.gz
    # Builds
    - sudo mkdir -p /builds
    - sudo chmod a+rw /builds

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get install -y libqt4-dev
    - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
    # Qt4
    - pushd /builds
    # SIP
    - tar xzf /downloads/sip.tar.gz --keep-newer-files
    - pushd sip-4.18.1
    - python configure.py
    - make
    - sudo make install
    - popd
    # PyQt4
    - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
    - pushd PyQt-x11-gpl-4.11.4
    - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtTest -e QtSvg
    - make
    - sudo make install
    - popd
    # Builds Complete
    - popd
    - pip install -U -r requirements.txt
    - pip install -U nose coverage coveralls codecov

script:
    - nosetests --with-coverage --cover-package=har2tree tests/test.py

after_success:
    - codecov
    - coveralls
