language: python

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"

install:
    - pip install -U -r requirements.txt
    - pip install -U nose coverage coveralls codecov

script:
    - nosetests --with-coverage --cover-package=har2tree tests/test.py

after_success:
    - codecov
    - coveralls
