language: python

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - pipenv run nosetests --with-coverage --cover-package=har2tree tests/test.py
    - pipenv run mypy --no-strict-optional .

after_success:
    - pipenv run codecov
    - pipenv run coveralls
